abhi@DESKTOP-TBD1H2I:~$ cd Cryptophilic
abhi@DESKTOP-TBD1H2I:~/Assignment5$ g++ analyze.cpp -o a
abhi@DESKTOP-TBD1H2I:~/Assignment5$ ./a
Pseudo-terminal will not be allocated because stdin is not a terminal.
students@172.27.26.188's password: cs641a
---(Series of TERM environment variable not set. : when the code runs)---
a 0
b 0
c 0
d 0
e 0
f 1506
g 1528
h 1493
i 1487
j 1469
k 1513
l 1473
m 1504
n 515
o 511
p 504
q 513
r 502
s 471
t 496
u 499
v 0
w 0
x 0
y 0
z 0
abhi@DESKTOP-TBD1H2I:~/Assignment5$ g++ inp-outp-gen.cpp -o a
abhi@DESKTOP-TBD1H2I:~/Assignment5$ ./a
Pseudo-terminal will not be allocated because stdin is not a terminal.
students@172.27.26.188's password:cs641a
---(Series of TERM environment variable not set. : when the code runs)---
abhi@DESKTOP-TBD1H2I:~/Assignment5$ g++ diag-elem.cpp -o a
diag-elem.cpp: In function ‘int main()’:
diag-elem.cpp:45:19: warning: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’
   45 |         for (auto [a, e] : adj[i])
      |                   ^
./abhi@DESKTOP-TBD1H2I:~/Assignment5$ ./a
For i = 1: (27, 1) ; (84, 19) ; (84, 107) ;
For i = 2: (35, 73) ; (70, 117) ; (84, 64) ;
For i = 3: (14, 89) ; (43, 40) ; (72, 125) ;
For i = 4: (12, 75) ; (24, 28) ; (30, 24) ;
For i = 5: (67, 105) ; (109, 59) ; (112, 90) ;
For i = 6: (11, 50) ; (86, 16) ; (97, 61) ;
For i = 7: (27, 21) ; (63, 88) ; (123, 18) ;
For i = 8: (9, 101) ; (38, 14) ; (108, 12) ;
abhi@DESKTOP-TBD1H2I:~/Assignment5$ g++ A-E-Password-finder.cpp -o a
A-E-Password-finder.cpp: In function ‘int main()’:
A-E-Password-finder.cpp:46:19: warning: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’
   46 |         for (auto [a11, e1] : adj[i - 1])
      |                   ^
A-E-Password-finder.cpp:48:23: warning: structured bindings only available with ‘-std=c++17’ or ‘-std=gnu++17’
   48 |             for (auto [a22, e2] : adj[i])
      |                       ^
abhi@DESKTOP-TBD1H2I:~/Assignment5$ ./a

Matrix A :

84 0 0 0 0 0 0 0
115 70 0 0 0 0 0 0
15 28 43 0 0 0 0 0
96 22 26 12 0 0 0 0
96 42 3 110 112 0 0 0
28 43 19 51 111 11 0 0
10 120 21 101 31 94 27 0
90 12 94 25 12 71 7 38

E : [19 117 40 75 90 50 21 14]

Password : svqqbwnkdm000000
abhi@DESKTOP-TBD1H2I:~/Assignment5$